### ISSUE TITLE
The docker image is quite large

### ISSUE THREAD

**Issue by Arjailer** [varthe/Defaulterr#17]
It's 3 times the size of the Plex image

![image](https://github.com/user-attachments/assets/1535bb0e-1a76-4f28-a76c-9e5f84b58939)

This is the arm64 image on a Raspberry Pi 4

It's not really a problem - I have plenty of space - it just stuck out  😃

**Comment by varthe** [comment]
Thanks for letting me know, it shouldn't be this big.

Changing to the alpine version of node brought it down to 190mb... lol
I added a dockerignore and its down to 169mb. From reading online the expected size of a node app with a few dependencies is 200-400mb.

Mind giving it a go on your pi?

**Comment by Arjailer** [comment]
Yep, that's a lot smaller  😄 

![image](https://github.com/user-attachments/assets/5ec046eb-e4a0-4760-9166-f3d90333ef8c)

I don't have any new files for Defaulterr to process, but the logs look like it started up okay  👍
