### ISSUE TITLE
ENHANCEMENT: turn off subtitles

### ISSUE THREAD

**Issue by hacktek** [varthe/Defaulterr#20]
Use case: a native language speaker will typically have no use for subtitles once the audio is set to their native language (for example, after setting audio to spanish on a library that includes only movies with at least 1 audio track in spanish). I'd like to be able to automatically set subtitles to off in that library, on top of setting the audio track to spanish.

I tried to do this via filters but it doesn't seem possible.

**Comment by varthe** [comment]
It will depend on whether we can "unselect" subtitle streams with Plex API. I will investigate over the weekend and see if its possible.

If I understand correctly, you want to disable subtitles when a Spanish audio track is present, but keep them enabled otherwise?

**Comment by hacktek** [comment]
Yeah, that would work! Thank you.

I'm not sure if this is exposed by the API, but when disabling subtitles in the web app it triggers a request to `/library/parts/########?subtitleStreamID=0&allParts=1`, (where ######## = part ID) so requesting that with the managed user's token should be enough.

**Comment by varthe** [comment]
Oh yeah that will work.
Now on how to implement it... I think having a `on_match` property along the include/exclude with an overriding subtitle filter will work best. We can add more to it in the future as well.

And also the ability to disable subtitles.

I'll add them in after I'm done with the tautulli bug.

**Comment by varthe** [comment]
@hacktek All done. Pull the latest image and check the new config

**Comment by hacktek** [comment]
Hey, thanks for working on this on a weekend lol

I tried it, modified my config this way:

```
filters:
  Peliculas:
    inSpanish:
      audio:
        - include:
            language: Español
          on_match:
            subtitles: disabled
          exclude:
            codec: truehd
            extendedDisplayTitle: commentary
        - include:
            language: Español
          on_match:
            subtitles: disabled
```

but after running it just stays here:

```
defaulterr  | 2024-10-20T00:49:56.280Z [info]: YAML file is valid according to the schema.
defaulterr  | 2024-10-20T00:49:56.286Z [info]: Server is running on port 3184
defaulterr  | 2024-10-20T00:49:56.612Z [info]: Finished processing managed users
defaulterr  | 2024-10-20T00:49:56.613Z [info]: Fetched and stored user details successfully.
defaulterr  | 2024-10-20T00:49:56.619Z [info]: Mapped library: Peliculas (ID: 56, Type: movie)
defaulterr  | 2024-10-20T00:49:56.619Z [info]: Fetched and mapped all relevant libraries.
```

Is there any additional debug level I could set it to so I can get more log messages? Cheers

EDIT: hmm, I commented out the new on_match and it's still getting stuck there.

EDIT2: with dry run it prints out the right messages:

```
defaulterr  | 2024-10-20T00:59:00.886Z [info]: YAML file is valid according to the schema.
defaulterr  | 2024-10-20T00:59:00.892Z [info]: Server is running on port 3184
defaulterr  | 2024-10-20T00:59:01.259Z [info]: Finished processing managed users
defaulterr  | 2024-10-20T00:59:01.259Z [info]: Fetched and stored user details successfully.
defaulterr  | 2024-10-20T00:59:01.265Z [info]: Mapped library: Peliculas (ID: 56, Type: movie)
defaulterr  | 2024-10-20T00:59:01.266Z [info]: Fetched and mapped all relevant libraries.
defaulterr  | 2024-10-20T00:59:01.266Z [info]: STARTING DRY RUN. NO CHANGES WILL BE MADE.
defaulterr  | 2024-10-20T00:59:01.266Z [info]: Processing library for dry run: Peliculas
defaulterr  | 2024-10-20T00:59:01.380Z [info]: Part ID 2806052: match found for audio stream Español (EAC3 5.1)
defaulterr  | 2024-10-20T00:59:01.380Z [info]: Part ID 2806052: subtitles disabled
defaulterr  | 2024-10-20T00:59:01.488Z [info]: Part ID 2831102: match found for audio stream Español (AC3 5.1)
defaulterr  | 2024-10-20T00:59:01.488Z [info]: Part ID 2831102: subtitles disabled
defaulterr  | 2024-10-20T00:59:01.594Z [info]: Part ID 2842232: match found for audio stream Español (EAC3 5.1)
defaulterr  | 2024-10-20T00:59:01.594Z [info]: Part ID 2842232: subtitles disabled
```

**Comment by varthe** [comment]
Looks like it saved the timestamps from your last run so its only updating new items added since then.
There should be a file called `last_run_timestamps.json` in your config volume. Delete it.

**Comment by varthe** [comment]
If you pull the latest image there is now an option to do a "clean" run on application start.

**Comment by hacktek** [comment]
That did it! Thank you!
