### ISSUE TITLE
No users have access to libraries

### ISSUE THREAD

**Issue by vinlow2015** [varthe/Defaulterr#36]
Have tried configuring the managed users section and even for myself, it indicates that all of the users including myself (server owner), are unable to access the libraries, when we can in fact, access it.

Not sure what I am doing wrong here.

Logs

```
2024/12/18 11:31:53 | stdout | 2024-12-18 03:31:53 [WARN]: No users have access to library TV Shows. Skipping
-- | -- | --
2024/12/18 11:31:53 | stdout | 2024-12-18 03:31:53 [WARN]: User user3 of group default can't access library TV Shows. They will be skipped during updates. Request failed with status code 401
2024/12/18 11:31:53 | stdout | 2024-12-18 03:31:53 [WARN]: User user2 of group default can't access library TV Shows. They will be skipped during updates. Request failed with status code 401
2024/12/18 11:31:53 | stdout | 2024-12-18 03:31:53 [WARN]: User user1 of group default can't access library TV Shows. They will be skipped during updates. Request failed with status code 401
2024/12/18 11:31:53 | stdout | 2024-12-18 03:31:53 [WARN]: User  of group default can't access library TV Shows. They will be skipped during updates. Request failed with status code 401
2024/12/18 11:31:53 | stdout | 2024-12-18 03:31:53 [WARN]: User Vin Low of group default can't access library TV Shows. They will be skipped during updates. Request failed with status code 404
```

**Comment by vinlow2015** [comment]
All of the managed users have access to all libraries: 
![Untitled](https://github.com/user-attachments/assets/25368ce3-3aec-4532-a8d6-a4db0179656c)

**Comment by varthe** [comment]
Are you saying that it was working before, but after adding managed users it stopped working for everyone including the already existing users? If so that is a bug. Can you try without any managed to see if it works? Also send your config

Double check the managed users' tokens. See README: [https://github.com/varthe/Defaulterr?tab=readme-ov-file#managed-accounts-optional](https://github.com/varthe/Defaulterr?tab=readme-ov-file#managed-accounts-optional)

**Comment by vinlow2015** [comment]
Sorry I should have been clearer, this is an initial config setup.

When I removed the managed section it gives an similar error stating that my user which is the server owner is unable to access the library as well.


logs:

```
2024/12/18 21:09:19 | stdout | 2024-12-18 21:09:19 [WARN]: No users have access to library TV Shows. Skipping
-- | -- | --
2024/12/18 21:09:19 | stdout | 2024-12-18 21:09:19 [WARN]: User  of group default can't access library TV Shows. They will be skipped during updates. Request failed with status code 401
2024/12/18 21:09:19 | stdout | 2024-12-18 21:09:19 [WARN]: User vinlowww of group default can't access library TV Shows. They will be skipped during updates. Request failed with status code 404
2024/12/18 21:09:19 | stdout | 2024-12-18 21:09:19 [INFO]: Processing library: TV Shows
```

config:
```
# REQUIRED
plex_server_url: "http://192.168.0.235:32400/"
plex_owner_name: "abcdefg" # Use this value in place of username to include the owner in groups
plex_owner_token: "xxx"
plex_client_identifier: "xxx" # See README on how to obtain
# REQUIRED END

# RUN SETTINGS
dry_run: False # For testing filters; won't update users. Recommended to test a few times to ensure filters work.

# PARTIAL RUN: Updates newly added media since the last run.
# WARNING: The first run will update all existing media. Subsequent runs will be faster.
partial_run_on_start: False
partial_run_cron_expression: "" # E.g., '0 3 * * *' to run every day at 3:00 am. See crontab.guru
# CLEAN RUN: Updates all existing media. Should only be used if you want to re-apply a new set of filters on your libraries.
clean_run_on_start: True
# RUN SETTINGS END

# MANAGED ACCOUNTS (optional)
# managed_users:
   # user1: "token1"
   # user2: "token2"
   # user3: "token3"
# MANAGED USERS END

# GROUPS
groups:
  default:
    - $ALL # Will grab all users with access to the library
# GROUPS END

# FILTERS - See README for explanation
filters:
  Movies:
    default:
      audio:
        - include:
            language: Chinese
          on_match:
            subtitles:
                - include:
                    language: Chinese
        - include:
            language: English, Korean, Japanese
          on_match:
            subtitles:
                - include:
                    language: English
  TV Shows:
    default:
      audio:
        - include:
            language: Chinese
          on_match:
            subtitles:
                - include:
                    language: Chinese
        - include:
            language: English, Korean, Japanese
          on_match:
            subtitles:
                - include:
                    language: English
```

**Comment by vinlow2015** [comment]
I think I probably misconfigured it, but not sure where it occurred. 

Is `plex_owner_name` supposed to be the username? 

And is the `plex_owner_token` supposed to be gotten from this method listed here? https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

**Comment by varthe** [comment]
Ah okay. Looks like something is wrong with the config then. Plex owner name can be anything. Check these:

- Library names inside `filters` should be EXACTLY like in Plex. E.g your library in plex should be exactly `TV Shows` including capital letters. The logs say this library could not be found.
- `plex_client_identifier` has to belong to the server, not the owner. Check this section of the README: [https://github.com/varthe/Defaulterr?tab=readme-ov-file#obtaining-the-client-identifier](https://github.com/varthe/Defaulterr?tab=readme-ov-file#obtaining-the-client-identifier). Look through the list and find the one with your SERVER'S name in it. Use that client identifier.

If these don't fix it post all logs from application startup to the end.

Also multiple values in the filters should be listed like this:
```
- include:
    language: 
      - English
      - Korean
      - Japanese
```

**Comment by vinlow2015** [comment]
What about the `plex_owner_token` ? Should I follow this link: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

**Comment by vinlow2015** [comment]
Here are the full logs:

![image](https://github.com/user-attachments/assets/20912982-04c7-4d32-a0aa-bac2c0ccf757)

**Comment by vinlow2015** [comment]
The library names are exactly as per what is in Plex, so im thinking the issue could be the `plex_*` portion config.

**Comment by vinlow2015** [comment]
I found the issue, `plex_server_url` should not have '/' at the back 🤦, looks to be running fine now. Thanks alot for your help!
