### ISSUE TITLE
Image for ARM64

### ISSUE THREAD

**Issue by varthe** [varthe/Defaulterr#7]
Make a second image for ARM64 devices

**Comment by Arjailer** [comment]
Seconded!

Just tried to install this on my Raspberry Pi 4 and found out it doesn't have an arm64 image  🙁

**Comment by varthe** [comment]
Coming in the next release sometime this weekend. I'll tag you when its out

**Comment by varthe** [comment]
@Arjailer the latest image should run on arm64 now

**Comment by Arjailer** [comment]
Thanks - got it running now and setting up a config file  👍
